pub const DAYS: [fn() -> (String, String); 25] = [
    || (String::new(), String::new()),
    || (String::new(), String::new()),
    || (String::new(), String::new()),
    || (String::new(), String::new()),
    || (String::new(), String::new()),
    || (String::new(), String::new()),
    || (String::new(), String::new()),
    || (String::new(), String::new()),
    || (String::new(), String::new()),
    || (String::new(), String::new()),
    || (String::new(), String::new()),
    || (String::new(), String::new()),
    || (String::new(), String::new()),
    || (String::new(), String::new()),
    || (String::new(), String::new()),
    || (String::new(), String::new()),
    || (String::new(), String::new()),
    || (String::new(), String::new()),
    || (String::new(), String::new()),
    || (String::new(), String::new()),
    || (String::new(), String::new()),
    || (String::new(), String::new()),
    || (String::new(), String::new()),
    || (String::new(), String::new()),
    || (String::new(), String::new()),
];
